### ISSUE TITLE
верстка компонента CardInfo

### ISSUE THREAD

**Issue by AlinaLvova** [HR-filter/frontend#28]
- [ ] 

![Image](https://github.com/HR-filter/frontend/assets/37267494/8c07b8ab-1b3d-43b6-9fd8-0ad300397646)

- [ ] 

![Image](https://github.com/HR-filter/frontend/assets/37267494/95a3bde6-0354-4659-b4d3-eea9811877f2)

Спроси у дизайнеров по поводу кнопок в графе порфолио, может пока обойтись ссылками?

**Comment by kavabunga** [comment]
Сделал ПР, чекните плз, @AlinaLvova @ConstantineEpifanov https://github.com/HR-filter/frontend/pull/33/

**Comment by kavabunga** [comment]
Пофиксил чуть стили и добавил типизацию для входящих данных https://github.com/HR-filter/frontend/pull/37

**Comment by kavabunga** [comment]
Отрефакторил и разбил на компоненты это все здесь: https://github.com/HR-filter/frontend/pull/47
